version: "3"
services:
  db:
    image: postgres:16.0
    restart: always
    volumes:
      - ./data/db:/var/lib/postresql/data
    ports:
      - 5432:5432

    environment:
      - POSTGRES_DB=DEMODB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=localhost

  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - 8080:8080

  next-app:
    build:
      dockerfile: dev.dockerfile

    env_file:
      - .env.dev

    volumes:
      - .:/app

    restart: always
    ports:
      - 3000:3000
